name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics-left:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_people: yes
          plugin_people_types: followers
          config_css: |
            svg { background: #0d1117; border-radius: 12px; }
            text, tspan { fill: #c9d1d9; }
            .field, .field svg { color: #7ee0ff; fill: #7ee0ff; }
            a { color: #7ee0ff; }

  github-metrics-right:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.right.svg
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_anilist: yes
          plugin_anilist_user: frewily
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_steam: yes
          plugin_steam_user: "76561199873735780"
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_sections: recently-played
          plugin_steam_recent_limit: 4
          config_css: |
            svg { background: #0d1117; border-radius: 12px; }
            text, tspan { fill: #c9d1d9; }
            .field, .field svg { color: #7ee0ff; fill: #7ee0ff; }
            a { color: #7ee0ff; }
